### ISSUE TITLE
User should be able to pick a subscription plan

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#14] opened 2019-08-14 20:30 UTC
**What:** User should be able to pick a subscription plan

User can choose from different donation tiers.

**How:**

- User can choose from different donation tiers.
- User can only choose one donation tier.

**Comment by castrolem** [comment] 2019-08-15 13:50
@orlando isn't this a duplicate of #13 ?

**Comment by orlando** [comment] 2019-08-15 14:39
@castrolem just to have the feature that we will have multiple plans in another ticket. A PR can close both

**Closed as completed** 2019-09-02 17:09 UTC
Labels: enhancement
